spring.application.name=banking-management

spring.datasource.url=jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
spring.datasource.username=kcepeda
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=truenate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.fail-on-empty-beans=false

spring.jackson.time-zone=America/Guayaquil